### ISSUE TITLE
Naming of jobs, processes, deployments jobs, etc

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-notes#12]
Initial proposal: https://github.com/cloudfoundry/bosh-notes/blob/master/deployment-naming.md

**Comment by cppforlife** [comment]
cc @allomov @Amit-PivotalLabs @voelzmo

**Comment by allomov** [comment]
I agree with you, that’s it a good field for improvement and I like this idea.

For instance it was very confusing for me at first having `jobs_instances` and `vms` in [the code](https://github.com/cloudfoundry/bosh/blob/ede389a2e112e1b4f2dbc4495c08977da4439483/bosh-director/lib/bosh/director/models/deployment.rb#L7-L8), since VMs can be called instances ssometimes. Understanding what's job and what's template is also not easy for newcomers, and changing things will benefit everyone.

I think that illustrating this proposal with manifest examples will let us easier catch up the idea. Here is an example I came across:
```yaml
deployment: cf-with-all-you-can-imagine
director_uuid: some-hash
clusters:
- name: cf
  nodes:
  - name: uaa
    count: 2
    type: small
    jobs:
    - name: uaa
      count: 2
      processes:
        - name: uaa
          name: metron-agent
      ...
  properties:
    ...
- name: mongo-db
  nodes:
  ...
  properties:
    ...
- name: cassandra
  ...
  properties:
    ...
```

As far as I understood `Node` corresponds to a "VM type" (or warden container in case with `bosh-lite`) that hosts the same jobs. Jobs are such logic groups of Processes for performing some task. The `processes` field here is analogue for current `templates` field in a job item.

Could you tell me if I got the idea right?

At this moment I have following questions: 

- Are you going to isolate jobs from each other by putting them to containers? 
- You used to say that jobs are typically long running, but what about errand jobs then?
